"""Add status

Revision ID: dccdf24a9495
Revises: f20b2c29dd35
Create Date: 2025-11-09 11:19:40.064841

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dccdf24a9495'
down_revision = 'f20b2c29dd35'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('reading',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('book_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.Enum('WISHLIST', 'TBR', 'READING', 'READ', name='bookstatus'), nullable=True),
    sa.Column('current_page', sa.Integer(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['book_id'], ['book.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('book_id')
    )
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('number_of_pages', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('added_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.drop_column('added_at')
        batch_op.drop_column('number_of_pages')

    op.drop_table('reading')
    # ### end Alembic commands ###
