"""Change url to cover_url

Revision ID: f20b2c29dd35
Revises: 90624ef9a781
Create Date: 2025-11-09 10:54:15.031085

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'f20b2c29dd35'
down_revision = '26c7181e107f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_url', sa.String(length=256), nullable=False))
        batch_op.drop_column('url')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('book', schema=None) as batch_op:
        batch_op.add_column(sa.Column('url', sa.VARCHAR(length=256), autoincrement=False, nullable=False))
        batch_op.drop_column('cover_url')

    # ### end Alembic commands ###
