"""Ajout de la date de publication au modèle Book

Revision ID: f727baa39259
Revises:
Create Date: 2025-09-22 21:36:24.560923

"""

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision = "f727baa39259"
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "book",
        sa.Column("id", sa.Integer(), nullable=False),
        sa.Column("title", sa.String(length=150), nullable=False),
        sa.Column("author", sa.String(length=100), nullable=False),
        sa.Column("published_date", sa.DateTime(), nullable=True),
        sa.PrimaryKeyConstraint("id"),
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("book")
    # ### end Alembic commands ###
